### ISSUE TITLE
Overloading Style and/or font

### ISSUE THREAD

**Issue by magno32** [comtel2000/fx-experience#13]
I am trying to replace the "Power" symbol in the bottom  right of the keyboard with something else, as the power symbol does not really make sense for my use-case.  

I have tried overloading ``` #key-button.button .done-icon { ... }``` in css, but this does not appear to be used.  It also looks like the ```.style()``` method in the builder doesn't let me change the style.  Is there a way to do this currently?

**Comment by comtel2000** [comment]
The current xml layout use font icons from FontKeyboardFX.ttf because of rendering quality. All the css -fx-shape stuff is no longer used. Please try to change the keyboard xml layout to:

```xml
<Key codes="-3" keyLabel="" keyIconStyle=".my-icon" keyWidth="50" />
```

and add the style class to your css:

```css
.my-icon {
-fx-shape:
		"m 15.072392,63.55427 a 0.74363458,0.74363458 0 0 0 -0.715759,0.775405 l 0,3.757729 a 0.74558131,0.74558131 0 0 0 1.491162,0 l 0,-3.757729 A 0.74363458,0.74363458 0 0 0 15.072392,63.55427 z m -2.385861,1.37187 a 0.74363458,0.74363458 0 0 0 -0.17894,0.05965 c -2.5661184,1.026488 -4.413841,3.577414 -4.413841,6.501469 0,3.834998 3.143892,6.918995 6.978642,6.918995 3.834746,0 6.97864,-3.084246 6.97864,-6.918995 0,-2.923456 -1.848399,-5.474601 -4.413842,-6.501469 a 0.74363458,0.74363458 0 1 0 -0.536818,1.37187 c 2.013874,0.806092 3.459497,2.818881 3.459497,5.129599 0,3.031265 -2.456217,5.427832 -5.487477,5.427832 -3.031263,0 -5.4874794,-2.396816 -5.4874794,-5.427832 0,-2.311044 1.4448634,-4.323714 3.4594964,-5.129599 a 0.74363458,0.74363458 0 0 0 -0.357878,-1.431516 z";

}
```

That still works for me.
